apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-vault-js-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: name-vault-js
  template:
    metadata:
      labels:
        app: name-vault-js
    spec:
      containers:
      - name: name-vault-js
        image: {{ .Values.app.image }}
        imagePullPolicy: Always   # <-- Add this line
        ports:
        - containerPort: {{ .Values.app.port }}
        env:
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_URI
        - name: PORT
          value: "{{ .Values.app.port }}"