apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: name-vault
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/masumshamsur/name-vault-js.git
    targetRevision: main
    path: name-vault-js-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: name-vault-js

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
